services:
  - type: web
    name: urbansetu
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO
        sync: false
      - key: JWT_TOKEN
        sync: false
    healthCheckPath: /api/health

  - type: static
    name: urbansetuglobal
    env: static
    plan: free
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: ./web/dist
    routes:
      - type: redirect
        source: /sitemap.xml
        destination: https://urbansetu-pvt4.onrender.com/sitemap.xml?domain=global
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://urbansetu-pvt4.onrender.com
